### ISSUE TITLE
SRC blocks are highlighted now

### ISSUE THREAD

**Issue by japhir** [integral-dw/org-superstar-mode#14] opened 2020-04-15 23:43 UTC
Looks like src blocks are highlighted using the `-`, `+`, and `*` elements now.

I create a SRC diff in one of my files, and all the +'s are replaced by `➤`.  This also appears to be the case when I create an empty 

```
#+BEGIN_SRC
+ hey
  - this
  * should not be fontified
#+END_SRC
```
![2020-04-16-01:44:58_region](https://user-images.githubusercontent.com/10659193/79399546-f2d96c00-7f83-11ea-85cd-153ac5aa7709.png)

This was perhaps introduced by https://github.com/integral-dw/org-superstar-mode/commit/3fbfc0a47ec3a828245d0de2c1c774229af20bb8?

**Comment by integral-dw** [comment] 2020-04-16 23:42
The issue was caused by me forgetting an `and` clause when changing a predicate back in 026c54f.
It's fixed now, but suggests that I should not put __v1.1.0-1.2.0__ on MELPA stable, as both had the bug.

**Comment by integral-dw** [comment] 2020-04-17 00:01
*v1.2.1* is now available, fixing the bug.  Thanks a lot for notifying me!

**Closed by integral-dw** 2020-04-17 00:01 UTC
Labels: bug
